kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: argocd-v2-9-0-examples
nodes:
- role: control-plane
- role: worker
- role: worker
- role: worker
  extraPortMappings:
    - containerPort: 31443  # NodePort for Argo CD `argocd-server` service (dashboard).
      hostPort: 8080  # Port on host running the kind cluster.