apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: argocd
namespace: argocd
resources:
- ./namespace.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.9.1/manifests/ha/install.yaml

patches:
  - path: ./service.yaml

components:
## Enable for Dynamic Shard Re-Balancing.
- ../dynamic-shard-rebalance/