apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ignore-applicationset-differences
spec:
  destination:
    namespace: argocd
    name: in-cluster
  project: default
  source:
    path: ignore-applicationset-differences/
    repoURL: https://github.com/ishitasequeira/argocd-v2.9.0-examples.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
