apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomize-patches-support
spec:
  destination:
    namespace: argocd
    name: in-cluster
  project: default
  source:
    path: kustomize-patches-support/
    repoURL: https://github.com/ishitasequeira/argocd-v2.9.0-examples.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
